# Backend configuration
backend:
  image:
    repository: my-backend-image
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 5000
  servicePort: 5000
  resources:
    limits:
      memory: "128Mi"
      cpu: "100m"
    requests:
      memory: "64Mi"
      cpu: "50m"

# Frontend configuration
frontend:
  image:
    repository: my-frontend-image
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 80
  servicePort: 80
  resources:
    limits:
      memory: "128Mi"
      cpu: "100m"
    requests:
      memory: "64Mi"
      cpu: "50m"

# HPA settings
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

# Debugbox (optional pod for debugging inside the cluster)
debugbox:
  enabled: false  # Set to true only when needed
  image: nicolaka/netshoot
  resources:
    limits:
      memory: "64Mi"
      cpu: "50m"
    requests:
      memory: "32Mi"
      cpu: "25m"
