apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vignesh-app.fullname" . }}-backend-secret
  labels:
    app: {{ include "vignesh-app.name" . }}
    component: backend
type: Opaque
data:
  api-token: {{ .Values.backend.secretToken | b64enc }}
