---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vignesh-app-backend
  namespace: team-a
  labels:
    app: vignesh-app
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vignesh-app
      component: backend
  template:
    metadata:
      labels:
        app: vignesh-app
        component: backend
    spec:
      serviceAccountName: app-sa
      containers:
        - name: backend
          image: vignesh/backend:latest
          command: ["/bin/sh"]
          args:
            - -c
            - |
              pip install flask flask-cors && python /app/app.py
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: app-volume
              mountPath: /app/app.py
              subPath: app.py
            - name: secret-volume
              mountPath: /secrets
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      volumes:
        - name: app-volume
          configMap:
            name: vignesh-app-backend-app
        - name: secret-volume
          secret:
            secretName: vignesh-app-backend-secret
