apiVersion: v1
kind: Service
metadata:
  name: {{ include "vignesh-app.fullname" . }}-backend
  labels:
    app: {{ include "vignesh-app.name" . }}
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.containerPort }}
      protocol: TCP
  selector:
    app: {{ include "vignesh-app.name" . }}
    component: backend
