apiVersion: v1
kind: Pod
metadata:
  name: debugbox
  namespace: team-a
spec:
  containers:
  - name: curl
    image: alpine/curl:latest
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    resources:
      requests:
        cpu: "0"
        memory: "0"
      limits:
        cpu: "0"
        memory: "0"
  restartPolicy: Never
