apiVersion: v1
kind: Service
metadata:
  name: {{ include "vignesh-app.fullname" . }}-frontend
  labels:
    app: {{ include "vignesh-app.name" . }}
    component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.containerPort }}
      protocol: TCP
  selector:
    app: {{ include "vignesh-app.name" . }}
    component: frontend
