apiVersion: v1
kind: ConfigMap
metadata:
  name: vignesh-app-frontend-config
  namespace: team-a
data:
  index.html: |
    <html>
    <head><title>Frontend</title></head>
    <body>
      <h1>Welcome to Vignesh's App 🚀</h1>
      <p>Connecting to backend...</p>
      <div id="result">Loading token...</div>
      <script>
        fetch("http://vignesh-app-backend.team-a.svc.cluster.local:5000/token")
          .then(res => res.text())
          .then(data => document.getElementById("result").innerText = "Token: " + data)
          .catch(err => document.getElementById("result").innerText = "Error: " + err);
      </script>
    </body>
    </html>
